baseURL = "https://blog.starmedicalediting.com"
disablePathToLower = true
paginate = "6"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "hugo-geekblog"
title = "Star Medical Blog"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 9
startLevel = 1
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
[outputFormats.Atom]
baseName = "atom"
isHTML = false
isPlainText = false
mediaType = "application/atom+xml"
name = "Atom"
noUgly = true
permalinkable = false
rel = "alternate"
[outputFormats.outputs]
home = ["HTML", "ATOM"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML", "ATOM"]
[params]
geekblogLegalNotice = "https://thegeeklab.de/legal-notice/#contact-information"
geekblogPrivacyPolicy = "https://thegeeklab.de/legal-notice/#privacy-policy"
logo = "../../../static/uploads/brand.png"
[taxonomies]
author = "authors"
tag = "tags"
