baseURL = "https://blog.starmedicalediting.com"
disablePathToLower = true
paginate = "6"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "Blogpaper"
title = "Star Medical Blog"
[[menu.main]]
name = "Contact"
url = "https://test.starmedicalediting.com#contact"
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 9
startLevel = 1
[mediaTypes."application/atom+xml"]
suffixes = ["xml"]
[outputFormats.Atom]
baseName = "atom"
isHTML = false
isPlainText = false
mediaType = "application/atom+xml"
name = "Atom"
noUgly = true
permalinkable = false
rel = "alternate"
[outputFormats.outputs]
home = ["HTML", "ATOM"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML", "ATOM"]
[params]
geekblogLegalNotice = "https://blog.starmedicalediting.com"
geekblogPrivacyPolicy = "https://blog.starmedicalediting.com"
logo = "uploads/brand.svg"
navHome = "https://test.starmedicalediting.com"
navBlog = "https://blog.starmedicalediting.com"
[taxonomies]
author = "authors"
tag = "tags"
