---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: themes/hugo-geekblog/static
  label: static
  create: documents
  match: "*.svg"
  new_doc_ext: ".png"
- type: heading
  label: Blog
- type: directory
  path: content/post
  label: Post
  create: documents
  match: "*"
  templates:
  - post_with_video
  - post_existent
  - post_basic
  - post
- type: heading
  label: Configurations
- type: document
  path: config.toml
  label: Config
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.80.0
